name: Betterplace
version: '${project.version}'
main: com.lerokko.betterplace.Betterplace
api-version: 1.20
authors: [ lerokko ]
description: Adds new place behavior to block placing to help builders
website: lerokko.com
commands:
  bpunlock:
    description: toggle off rotation lock (betterplace.place.rotated)
    usage: /<command>
    permission: bplace.place.rotated